config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  resources :items, only: %i{index show}
  resources :categories, only: :index do
    resources :items, only: :index
  end
  resources :wished_items, only: %i(index show create destroy)
end

app/models/api_model.rb
module ApiModel
  module ClassMethods
    def all(options: {})
      json = Auctionet.fetch(type, params: options)
      json[type].map { |item| from_hash(item) }
    end

    def find(id, options: {})
      json = Auctionet.fetch(type, id: id, params: options)
      from_hash json[name.downcase]
    end

    def from_hash(hash)
      new *hash.values_at(*fields)
    end

    def fields
      members.map(&:to_s)
    end

    def type
      name.downcase.pluralize
    end
  end

  def self.included(receiver)
    receiver.extend ClassMethods
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < Struct.new(*%i(id name parent_id children))
  include ApiModel
end

app/models/item.rb
class Item < Struct.new(*%i(id title state url images
                            description currency estimate
                            next_bid_amount bids))

  include ApiModel
end

app/models/wished_item.rb
class WishedItem < ApplicationRecord
  validates :external_id, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = if params.has_key?(:category_id)
               @category = Category.find(params[:category_id])
               Item.all(options: { state: "published", category_id: @category.id })
             else
               Item.all(options: { state: "published" })
             end
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/wished_items_controller.rb
class WishedItemsController < ApplicationController
  def index
    @wished_items = WishedItem.all
  end

  def show
    @wished_item = WishedItem.find(params[:id])
  end

  def create
    @wished_item = WishedItem.new(wished_item_params)
    @wished_item.save!
    WishedItemUpdaterJob.new.perform(@wished_item.id)
  end

  def destroy
    @wished_item = WishedItem.find(params[:id])
    @wished_item.destroy
  end

  private

  def wished_item_params
    params.require(:wished_item).permit(:external_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.slim
h1 Categories

- @categories.each do |category|
  p= link_to category.name, category_items_path(category.id)

app/views/items/_item.html.slim
.col-sm-4.col-md-3
  .thumbnail
    img src="#{item.images[0]['w200']}"
    .caption
      h3= item.title
      p= item.description
      p= link_to "View", item_path(item.id), class: "btn btn-primary"
      p= render 'wished_items/add', external_id: item.id, klass: "btn btn-default"

app/views/items/index.html.slim
h1
  | Items
  = " in category '#{@category.name}'" if @category

- @items.each_slice(4) do |items_group|
  .row
    = render partial: 'item', collection: items_group

app/views/items/show.html.slim
h1= @item.title
p= @item.description
p= "Status: #{@item.state}"
p= "Next bid: #{@item.next_bid_amount} #{@item.currency}"
p= "Estimate: #{@item.estimate} #{@item.currency}"
p= "Number of bids: #{@item.bids.count}"
p= link_to @item.url, @item.url
.row
  .col-sm-12.col-md-12
    - @item.images.each do |image|
      img src="#{image['w200']}"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title Auctionet Wish List
    = csrf_meta_tags
    = action_cable_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/" Auctionet Wish List
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to "Items", items_path
            li= link_to "Categories", categories_path
            li= link_to "Wished Items", wished_items_path

    .container
      .row
        .col-lg-12
          = yield

      footer
        p
          ' &copy;
          '
          = Date.today.year

app/views/wished_items/_add.html.slim
= form_tag wished_items_path, remote: true do
  = hidden_field_tag :'wished_item[external_id]', external_id
  = submit_tag "Add to wish list", class: klass

app/views/wished_items/index.html.slim
h1 Wish list

- @wished_items.each do |wished_item|
  = wished_item.external_id
  = link_to 'Show', wished_item
  = link_to 'Destroy', wished_item, data: {confirm: 'Are you sure?'}, method: :delete

app/views/wished_items/show.html.slim
p#notice = notice

p
  strong Title:
  = @wished_item.title
p
  strong External:
  = @wished_item.external_id
p
  strong Description:
  = @wished_item.description
p
  strong Bids count:
  = @wished_item.bids_count
p
  strong Next bid:
  = @wished_item.next_bid
p
  strong State:
  = @wished_item.state